name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        if: ${{ runner.os == 'windows' }}
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Restore cake tool
        run: dotnet tool restore

      - name: Install dotnet workloads
        run: |
          dotnet workload install android ios tvos --skip-manifest-update

      - name: Build
        run: |
          dotnet cake

